# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentRecap < Formula
  desc "Unified TUI for browsing and resuming Claude Code and Codex CLI sessions"
  homepage "https://github.com/jaredatch/agent-recap"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaredatch/agent-recap/releases/download/v0.1.0/agent-recap_darwin_amd64.tar.gz"
      sha256 "5a52b96afbdc28727c25fefdc307e6621108f691ac0f12bbc0e6663b500d7555"

      define_method(:install) do
        bin.install "recap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaredatch/agent-recap/releases/download/v0.1.0/agent-recap_darwin_arm64.tar.gz"
      sha256 "3cb3e5fa702c32eccda6a686bb8fa187ad51eab65ddbc5d2805a03cd879c2e74"

      define_method(:install) do
        bin.install "recap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaredatch/agent-recap/releases/download/v0.1.0/agent-recap_linux_amd64.tar.gz"
      sha256 "990e8c8f957ca96480431471654a7a90c6c037020f50d7ad40c4c2339e970870"
      define_method(:install) do
        bin.install "recap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaredatch/agent-recap/releases/download/v0.1.0/agent-recap_linux_arm64.tar.gz"
      sha256 "66e9ed2c2a6710dde70584c1ba42c7fe03784b00142cf96997db715e968da4a7"
      define_method(:install) do
        bin.install "recap"
      end
    end
  end

  test do
    system "#{bin}/recap", "--version"
  end
end
